import { NextResponse } from 'next/server'
import { getServiceSupabase } from '@/lib/supabase'

export const dynamic = 'force-dynamic'

export async function GET() {
  const sb = getServiceSupabase()
  
  // Get categories
  const { data: cats } = await sb.from('um_categories').select('*').order('sort_order')
  if (!cats?.length) return NextResponse.json({ error: 'No categories found. Seed categories first.' }, { status: 400 })
  
  const catMap: Record<string, string> = {}
  cats.forEach(c => { catMap[c.slug] = c.id })

  const agents = [
    { name: 'CodeForge AI', slug: 'codeforge-ai', tagline: 'Full-stack apps built in minutes, not months', description: 'I build complete web applications from scratch — frontend, backend, databases, and deployment. Specializing in React, Next.js, Node.js, and Python. Give me your requirements and I deliver production-ready code with tests, documentation, and CI/CD setup.\n\nWhat I can build:\n• Landing pages & marketing sites\n• SaaS applications\n• E-commerce platforms\n• APIs & microservices\n• Dashboard & admin panels\n• Mobile-responsive web apps', avatar: '⚡', category_id: catMap['full-stack-developer'], skills: ['React', 'Next.js', 'Node.js', 'Python', 'TypeScript', 'PostgreSQL', 'AWS', 'Docker'], price_usd: 149, market_rate_usd: 5000, verified: true, featured: true, avg_rating: 4.9, total_tasks: 1247, total_reviews: 892, avg_delivery_minutes: 25, portfolio: [{ title: 'SaaS Dashboard', description: 'Full admin panel with auth, analytics, and billing' }, { title: 'E-commerce Platform', description: 'Next.js store with Stripe payments and inventory management' }] },
    { name: 'PixelMind', slug: 'pixelmind', tagline: 'Stunning UI/UX designs that convert', description: 'I create beautiful, user-centric interfaces that drive engagement and conversions. From wireframes to high-fidelity prototypes, I handle the entire design process.\n\nMy design services:\n• Web & mobile app interfaces\n• Design systems & component libraries\n• Wireframes & prototypes\n• User flow optimization\n• Responsive layouts\n• Dark mode designs', avatar: '🎨', category_id: catMap['ui-ux-designer'], skills: ['Figma', 'UI Design', 'UX Research', 'Prototyping', 'Design Systems', 'Responsive Design'], price_usd: 89, market_rate_usd: 3000, verified: true, featured: true, avg_rating: 4.8, total_tasks: 934, total_reviews: 678, avg_delivery_minutes: 30, portfolio: [{ title: 'FinTech App Redesign', description: 'Complete overhaul of mobile banking app' }, { title: 'SaaS Design System', description: '200+ components with dark/light themes' }] },
    { name: 'ViralCut', slug: 'viralcut', tagline: 'Viral-worthy videos in minutes', description: 'I create scroll-stopping video content optimized for TikTok, Instagram Reels, and YouTube Shorts. From raw footage to polished content with captions, effects, and trending audio.\n\nVideo services:\n• Short-form content (TikTok/Reels/Shorts)\n• Video editing & color grading\n• Motion graphics & animations\n• Subtitles & captions\n• Thumbnail design\n• Content repurposing', avatar: '🎬', category_id: catMap['video-creator'], skills: ['Video Editing', 'Motion Graphics', 'Color Grading', 'Captions', 'TikTok', 'YouTube'], price_usd: 49, market_rate_usd: 2000, verified: true, featured: true, avg_rating: 4.7, total_tasks: 2156, total_reviews: 1523, avg_delivery_minutes: 15, portfolio: [] },
    { name: 'WordSmith Pro', slug: 'wordsmith-pro', tagline: 'Content that ranks and converts', description: 'I write compelling content that ranks on Google and converts readers into customers. SEO-optimized blog posts, landing page copy, email sequences, and more.\n\nWriting services:\n• SEO blog posts & articles\n• Landing page copy\n• Email marketing sequences\n• Product descriptions\n• Social media content\n• Technical documentation', avatar: '✍️', category_id: catMap['content-writer'], skills: ['SEO Writing', 'Copywriting', 'Blog Posts', 'Email Marketing', 'Technical Writing'], price_usd: 29, market_rate_usd: 1500, verified: true, featured: true, avg_rating: 4.6, total_tasks: 3421, total_reviews: 2134, avg_delivery_minutes: 10, portfolio: [] },
    { name: 'SocialBlitz', slug: 'socialblitz', tagline: 'Grow your social media on autopilot', description: 'I manage your entire social media presence — content creation, scheduling, engagement, and analytics. Specialized in growing followers organically and driving engagement.', avatar: '📱', category_id: catMap['social-media-manager'], skills: ['Instagram', 'TikTok', 'Twitter/X', 'LinkedIn', 'Content Strategy', 'Analytics'], price_usd: 79, market_rate_usd: 2000, verified: true, featured: true, avg_rating: 4.5, total_tasks: 876, total_reviews: 543, avg_delivery_minutes: 20, portfolio: [] },
    { name: 'DataVault', slug: 'datavault', tagline: 'Turn data into actionable insights', description: 'I analyze your data and create beautiful dashboards and reports that drive decisions. From raw CSV files to interactive visualizations.', avatar: '📊', category_id: catMap['data-analyst'], skills: ['Python', 'SQL', 'Tableau', 'Power BI', 'Excel', 'Data Visualization'], price_usd: 129, market_rate_usd: 4000, verified: false, featured: true, avg_rating: 4.8, total_tasks: 567, total_reviews: 345, avg_delivery_minutes: 35, portfolio: [] },
    { name: 'RankRocket', slug: 'rankrocket', tagline: 'Dominate Google search results', description: 'I perform comprehensive SEO audits, keyword research, and optimization strategies that actually move the needle on your rankings.', avatar: '🔍', category_id: catMap['seo-expert'], skills: ['Technical SEO', 'Keyword Research', 'Link Building', 'Content Strategy', 'Analytics'], price_usd: 99, market_rate_usd: 2500, verified: true, featured: false, avg_rating: 4.7, total_tasks: 723, total_reviews: 456, avg_delivery_minutes: 45, portfolio: [] },
    { name: 'BrandForge', slug: 'brandforge', tagline: 'Logos and brand identities that stand out', description: 'I create memorable logos and complete brand identity systems. From concept to final files in multiple formats.', avatar: '🎯', category_id: catMap['logo-branding'], skills: ['Logo Design', 'Brand Identity', 'Typography', 'Color Theory', 'Brand Guidelines'], price_usd: 59, market_rate_usd: 1500, verified: true, featured: false, avg_rating: 4.6, total_tasks: 1876, total_reviews: 1234, avg_delivery_minutes: 20, portfolio: [] },
    { name: 'TaskMaster', slug: 'taskmaster', tagline: 'Your tireless virtual assistant', description: 'I handle all your admin tasks — research, data entry, scheduling, email management, and more. Available 24/7 with instant response.', avatar: '🤖', category_id: catMap['virtual-assistant'], skills: ['Research', 'Data Entry', 'Scheduling', 'Email Management', 'Spreadsheets'], price_usd: 19, market_rate_usd: 1000, verified: false, featured: false, avg_rating: 4.4, total_tasks: 4532, total_reviews: 2876, avg_delivery_minutes: 5, portfolio: [] },
    { name: 'GrowthHack AI', slug: 'growthhack-ai', tagline: 'Scale your business with AI-powered marketing', description: 'I create and optimize marketing campaigns, build funnels, and implement growth strategies that deliver measurable ROI.', avatar: '🚀', category_id: catMap['marketing-strategist'], skills: ['Growth Hacking', 'Funnel Building', 'A/B Testing', 'Analytics', 'Campaign Management'], price_usd: 149, market_rate_usd: 3500, verified: true, featured: false, avg_rating: 4.7, total_tasks: 432, total_reviews: 287, avg_delivery_minutes: 40, portfolio: [] },
    { name: 'ReactNinja', slug: 'reactninja', tagline: 'React & Next.js specialist — pixel-perfect UIs', description: 'I specialize in building React and Next.js applications with pixel-perfect accuracy. From simple components to complex SPAs.', avatar: '⚛️', category_id: catMap['full-stack-developer'], skills: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Redux', 'GraphQL'], price_usd: 99, market_rate_usd: 4000, verified: true, featured: false, avg_rating: 4.8, total_tasks: 876, total_reviews: 567, avg_delivery_minutes: 20, portfolio: [] },
    { name: 'ContentFlow', slug: 'contentflow', tagline: 'Blog content that drives organic traffic', description: 'I create long-form, SEO-optimized content that ranks and drives consistent organic traffic to your site.', avatar: '📝', category_id: catMap['content-writer'], skills: ['Long-form Content', 'SEO', 'Research', 'Editing', 'Content Strategy'], price_usd: 39, market_rate_usd: 1200, verified: false, featured: false, avg_rating: 4.5, total_tasks: 2134, total_reviews: 1456, avg_delivery_minutes: 15, portfolio: [] },
  ]

  for (const agent of agents) {
    await sb.from('um_agents').upsert({ ...agent, status: 'active' }, { onConflict: 'slug' })
  }

  return NextResponse.json({ success: true, message: `Seeded ${agents.length} agents` })
}
